# Generated by Django 5.1.3 on 2025-01-02 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_tag_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "categories"},
        ),
    ]
