# Generated by Django 5.1.3 on 2025-01-16 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_disount_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="disount_percentage",
            field=models.SmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(33),
                ],
            ),
        ),
    ]
