# Generated by Django 5.1.3 on 2025-01-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_disount_percentage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="disount_percentage",
            new_name="discount",
        ),
    ]
