# Generated by Django 5.1.3 on 2025-01-17 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_product_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.SmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
    ]
