# Generated by Django 5.1.3 on 2025-01-16 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_shippingaddress_country_order_orderitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name_plural": "Order Items"},
        ),
    ]
