# Generated by Django 5.1.3 on 2025-01-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="topic",
            name="name",
            field=models.CharField(db_index=True, default="Topic", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topic",
            name="slug",
            field=models.SlugField(default="topic", max_length=130, unique=True),
            preserve_default=False,
        ),
    ]
