# Generated by Django 5.1.6 on 2025-03-10 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupon",
            old_name="active",
            new_name="is_active",
        ),
    ]
